# Application Config Profilo STANDARD
# ==============================================================
# = info ACTUATOR
# ==============================================================
info:
  assistenza:
    nome: "Venanzio Figliolino"
    mail: "info@test.it"
  nome:
    nome-app: "Gestione Utenti Web Service - Versione authentiacata su GitHub"
    profilo : Git

# ==============================================================
# = MySql Parameters
# ==============================================================
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subitoclone?serverTimezone=UTC
    username: scadmin
    password: Checca-79
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true

# ==============================================================
# = Rabbit MQ
# ==============================================================
rabbitmq:
  host: 172.25.0.2
  port: 5672
  username: rabbitmq
  password: rabbitmq

# ==============================================================
# = ACTUATOR
# ==============================================================
management:
  endpoint:
    health:
      show-details: always
  #    show-details: when-authorized
  endpoints:
    web:
      exposure:
        include: health, info, metrics
        #include: "*"
